### ISSUE TITLE
Correlator and Verification Tests are failled when QCDGPU test executed

### ISSUE THREAD

**Issue by streamhsa** [vadimdi/QCDGPU#1]
In SU(N) Test Verification Test is failled see the snippshot 

![su n](https://cloud.githubusercontent.com/assets/8362518/21677422/16062a0c-d360-11e6-8d5d-141bf1644bce.PNG)

In O(N) Test Correlator and Verification Test are Failing see the snippshot  

![o n](https://cloud.githubusercontent.com/assets/8362518/21677420/1602c4b6-d360-11e6-9348-a58056a8e24f.PNG)

![o n _v](https://cloud.githubusercontent.com/assets/8362518/21677421/1606163e-d360-11e6-8d6b-5bcf05515f98.PNG)

**Please check the attached logs**

[QCDGPU_SU(N).txt](https://github.com/vadimdi/QCDGPU/files/687024/QCDGPU_SU.N.txt)
[QCDGPU_O(N).txt](https://github.com/vadimdi/QCDGPU/files/687025/QCDGPU_O.N.txt)

**Comment by vadimdi** [comment]
The issue was fixed for SU(N) model case.
O(N) model case is under investigation.
Thanks for the report.

**Comment by streamhsa** [comment]
thanks alot for your reply.
SU(N) model case is passing with new binaries. and let me know once O(N) model case issue fixed.

**Comment by vadimdi** [comment]
O(N) model code is also updated now

**Comment by streamhsa** [comment]
Thanks for your quick response Vadimdi,
with New Binaries both O(N) Model Case and SU(N) Model Case both are working fine.
