### ISSUE TITLE
Typo in #ifndef  or  #define resulting in error while compiling.

### ISSUE THREAD

**Issue by saipoorna** [vadimdi/QCDGPU#2]
Hi Vadimdi,

In call on_measurements_cl.cl 
**There seems to be a typo** 
#ifndef ONMEASU**RU**MENTSCL_CL
#define ONMEASU**RE**MENTSCL_CL

The latest compilers are throwing below error. FYI: Compiled succesfully after I corrected the typo locally.
ERROR -11: (clBuildProgram failed)
Build status:
þÿÿÿ
Build options:
-Werror -D ON_MODEL -D ACC_RATE -D SUN=1 -D ND=4 -D N1EXACT=18 -D N1=18 -D N2=18 -D N3=18 -D N4=4 -I /home/fpadmin/Desktop/Tests/OCL/ISV/QCDGPU/QCDGPU-master/O(N)/oncl/ -D SKGROUP=4 -I /home/fpadmin/Desktop/Tests/OCL/ISV/QCDGPU/QCDGPU-master/O(N)/kernel/ -D ROWSIZE=23360 -D PRECISION=1
Log:
/tmp/AMD_14405_25/t_14405_27.cl:38:9: error: 'ONMEASURUMENTSCL_CL' is used as a header guard here, followed by #define of a different macro [-Werror,-Wheader-guard]
#ifndef ONMEASURUMENTSCL_CL
        ^~~~~~~~~~~~~~~~~~~
/tmp/AMD_14405_25/t_14405_27.cl:39:9: note: 'ONMEASUREMENTSCL_CL' is defined here; did you mean 'ONMEASURUMENTSCL_CL'?
#define ONMEASUREMENTSCL_CL
        ^~~~~~~~~~~~~~~~~~~
        ONMEASURUMENTSCL_CL
1 error generated.
Error: Failed to compile opencl source (from CL to LLVM IR).

**Comment by vadimdi** [comment]
Thanks for report. The source code is fixed now.
(tested on CUDA, AMD APP and Intel OpenCL platforms)

**Comment by saipoorna** [comment]
Thanks Vadimdi. You might want to fix it in sun_measurements_cl.cl as well?

**Comment by vadimdi** [comment]
thanks! it's also fixed now (for both SU(N) and O(N) projects).
