### ISSUE TITLE
kernel compilation error due to private addr space in function return type

### ISSUE THREAD

**Issue by yxsamliu** [vadimdi/QCDGPU#3]
line 96 of neighbours.cl:
                    __attribute__((always_inline)) __private uint
lattice_even_gid(void)
{
    uint odd_check,gindex,gde;
    gde = 2 * GID;
    coords_4 coord;
    lattice_gid_to_coords(&gde,&coord);
    odd_check = (coord.x + coord.y + coord.z + coord.t) & 1;
    gindex = gde + odd_check;
    return gindex;
}
The return type has __private addr space. C language does not allow function return type to have address space. Recently clang was changed to use explicit private addr space in AST, which revealed this bug.

The fix is to remove __private from the function return type.

Same with neighbours.cl line 110 and o1_matrix_memory.cl line 42.

**Comment by vadimdi** [comment]
thanks for your report

it was introduced the following new preprocessor variables (to avoid possible backward incompatibility for very old drivers):

`#define HGPU_INLINE_PREFIX_VOID  __attribute__((always_inline)) // the list of qualifiers for void  inline functions`

`#define HGPU_INLINE_PREFIX       __attribute__((always_inline)) // the list of qualifiers for typed inline functions`
